### ISSUE TITLE
Migrate Mongo to ICSSC Account

### ISSUE THREAD

**Issue by chenaaron3** [icssc/peterportal-client#157]
Currently using PeterPortal's own Mongo account. Want to consolidate all accounts to ICSSC.

**Comment by ethanwong16** [comment]
- Might have to transfer reviews to new Mongo account

**Comment by ramanxg** [comment]
I think you can just transfer ownership of the project. https://www.mongodb.com/docs/atlas/tutorial/manage-projects/#move-a-project

**Comment by js0mmer** [comment]
#490
