### ISSUE TITLE
Close AddYear Popup when click away

### ISSUE THREAD

**Issue by chenaaron3** [icssc/peterportal-client#167]
Add year button, edit year button, mobile menu button will stay open even if the user clicks away. Make it so when user clicks away at anything else the menus will close.
![screen-capture-_8_](https://user-images.githubusercontent.com/44650208/155229837-beee9fbc-def1-44a0-b87c-f4b5b0ffc786.gif)

**Comment by js0mmer** [comment]
Use an [OverlayTrigger](https://react-bootstrap-v4.netlify.app/components/overlays/#overlay-trigger).

**Comment by js0mmer** [comment]
Fixed by #406 and #419
