### ISSUE TITLE
Allow users to select a quarter in Schedule of Classes

### ISSUE THREAD

**Issue by chenaaron3** [icssc/peterportal-client#201]
Currently, shows user the 'selected' option in websoc. Query all the options in websoc and allow users to choose from a dropdown.

**Comment by ethanwong16** [comment]
<img width="593" alt="Screen Shot 2022-06-03 at 14 38 29" src="https://user-images.githubusercontent.com/57075492/171957299-c9573e78-8b12-4f18-ab6a-b5e67fedd1e2.png">
^ have a dropdown to select other quarters here
- parse our current quarter from WebSoc + provide a few quarters before 

- https://github.com/icssc/peterportal-client/blob/28c39e6527f4766a3f8c8e60234c8a3f1c95c744/site/src/component/Schedule/Schedule.tsx
- "/api/currentQuarter" https://github.com/icssc/peterportal-client/blob/master/api/src/controllers/schedule.ts
- getCurrentQuarter() https://github.com/icssc/peterportal-client/blob/973a422bf7b621016d183919b41f2b5f298ec51b/api/src/helpers/currentQuarter.ts#L5
