### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by ChaseC99** [icssc/peterportal-client#216]
Add this site tag to your `index.html` file. 
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-R44HQTN9E1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-R44HQTN9E1');
</script>
```

If you want to add more advanced analytics, you can refer to this [AntAlmanac PR](https://github.com/icssc/AntAlmanac/pull/359)
@chenaaron3 has access to the google analytics account. Let me know if anyone else does too.

**Comment by chenaaron3** [comment]
Done
