### ISSUE TITLE
Current Week PPAPI

### ISSUE THREAD

**Issue by chenaaron3** [icssc/peterportal-client#224]
Use PPAPI's week endpoint to get the current week.

- [ ] Remove current implementation (api\src\helpers\week.ts)
- [ ] Change endpoint (api\src\controllers\schedule.ts) to use [ppapi implementaiton](https://api.peterportal.org/REST-API/schedule/#scheduleweek)

**Comment by js0mmer** [comment]
Blocked by #344 
New API will return correct results for fall quarter and will add support for concurrent terms during the summer.

Note: Our current implementation does handle fall quarter appropriately but does not support concurrent terms.
