### ISSUE TITLE
Update the Footer's GitHub Link

### ISSUE THREAD

**Issue by ChaseC99** [icssc/peterportal-client#227]
Currently the footer redirects to the old icssc-projects github. Update this to https://github.com/icssc
![image](https://user-images.githubusercontent.com/29494270/169726631-3b803cbe-9415-4575-8d7d-6b2906e4c023.png)

**Comment by svihang8** [comment]
Hello! I would like to work on this issue. @ChaseC99

**Comment by ChaseC99** [comment]
@svihang8 thanks for your interest but these tasks are reserved for UCI students.

**Comment by FireShadowLight** [comment]
I'll do this one!
