### ISSUE TITLE
Move review profanity text 

### ISSUE THREAD

**Issue by chenaaron3** [icssc/peterportal-client#229]
Move profanity text into the same section as the text box. Place it under the 'Tell us more..' text.
<img width="965" alt="Screen_Shot_2022-05-24_at_1 14 21_AM" src="https://user-images.githubusercontent.com/44650208/170154830-130240f1-2aa6-4930-aa04-93ce4b8e1dee.png">

**Comment by anthonytoribio** [comment]
I'll take this one.

**Comment by aahei** [comment]
The text was moved to the placeholder of the input textbox instead because I couldn't find an appropriate style for the description text if it were added below "Tell us...".

**Comment by aahei** [comment]
2/24 discussion: move the text below the textbox.

**Comment by aahei** [comment]
Done. PR #262
