### ISSUE TITLE
Filtering Courses by Major/Minor/GEs

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/peterportal-client#234]
Suggestion: Ability to add courses from a major/minor/ge filter. 

It's a big job, but I figured I should just throw it out there.

Example (https://zot4plan.com/):
![image](https://user-images.githubusercontent.com/64875104/192952673-120acdac-5c19-45b1-8da0-8a2eb26325f8.png)

**Comment by ethanwong16** [comment]
Thank you @MinhxNguyen7 for the suggestion!  We currently have another issue focused on adding filtering already open so I'll close and link this one to it.  We had the goal of including GE filters, but the major / minor filter is something new that is worth exploring as well.
