### ISSUE TITLE
Investigate Creating Banner for PeterPortal Mobile Mode

### ISSUE THREAD

**Issue by ethanwong16** [icssc/peterportal-client#239]
Consider changing UI to move "Week X - XXX" message and "Professor / Course" button down into a new bar right above the search bar

- consider if the bar should be dismissible
- consider adding fun messages (e.g. Happy halloween) to the "Week X - XXX" message
- moving professor / course search option toggle button so it's in a more intuitive place

![mobile_pp](https://user-images.githubusercontent.com/57075492/196303933-edcc1ba8-c1be-4e9f-a551-798a2b5c95e1.png)

**Comment by js0mmer** [comment]
Replaced by #524
