### ISSUE TITLE
Investigate 403 Bad Request error for "www.peterportal.org"

### ISSUE THREAD

**Issue by ethanwong16** [icssc/peterportal-client#242]
Currently when we visit [www.peterportal.org](www.peterportal.org), we receive a 403 Bad Request error and cannot enter the page.

Going to [peterportal.org](peterportal.org) without the preceding "www" has no issue.

This task should involve investigating the cause of this and exploring potential fixes (most likely just forwarding the www.peterportal.org directly to peterportal.org)

**Comment by js0mmer** [comment]
Fixed. Copied what antalmanac does and: set up a CNAME record for www pointing to a cloudfront distribution with a cloudfront function that redirects GET & HEAD requests to peterportal.org
