### ISSUE TITLE
Week Number Not Correct

### ISSUE THREAD

**Issue by aahei** [icssc/peterportal-client#244]
On the upper-right corner of the page, it displays the week number of the quarter. 
The week number is not correct. It is Week 10 on December 1st.
![image](https://user-images.githubusercontent.com/18681247/205177678-df5e876d-4c54-48c2-8511-3ebf525a5055.png)

**Comment by js0mmer** [comment]
Special case with fall quarter. Instruction start date is Thursday 9/22/2022, week 0. It is currently Thursday 12/1/2022 so the code calculates it to be week 11 already.
