### ISSUE TITLE
Adding perfectage into Grade Distribution page

### ISSUE THREAD

**Issue by ZL-Asica** [icssc/peterportal-client#246]
I think adding a percentage view will be better than a view of just numbers. Showing the percentage will be more intuitive to help users to judge, but of course, it is better to show both the percentage and the number.

**Comment by ethanwong16** [comment]
Thanks for the feedback!  We actually already have a "Pie" chart option on grade distributions which show a percentage rather than the raw quantity, but we will definitely look into whether to make the default if it is more intuitive :)
