### ISSUE TITLE
Investigate: Weird Pie Chart on Grade Distribution for P/NP Course

### ISSUE THREAD

**Issue by MFYLM** [icssc/peterportal-client#249]
<img width="488" alt="Screen Shot 2023-01-27 at 4 23 05 PM" src="https://user-images.githubusercontent.com/77956676/215229852-8824a1b3-f65b-4c77-b171-40dbd6824201.png">
I think we need to show a better pie chart for those N/NP classes to improve user experience. More discussion about chart design is needed.

**Comment by ethanwong16** [comment]
Goal
- look into which component / where in the codebase this is being rendered
- propose solution to fix it
- what changes we might need to make
- is it feasible to implement it?
