### ISSUE TITLE
Flickering of boards when course information is opened 

### ISSUE THREAD

**Issue by nicoleiftekhar** [icssc/peterportal-client#251]
Most boards flicker when opened to see course information, some do not.

**Comment by js0mmer** [comment]
I assume this refers to the fact that we have to fetch data for grade distribution, schedule of classes, etc. so initially those sections are empty until the data is received half a second later. While we can't do anything about needing to fetch data, we can implement a skeleton mode that displays an empty gray box of the same height/width of the information displayed while we are waiting for a response. This can prevent the section headings and width of the popup from shifting around.

https://github.com/icssc/peterportal-client/assets/8922227/140dc832-aa9b-4376-81fb-dba96e36a7ab

e.g. YouTube skeleton mode
![image](https://github.com/icssc/peterportal-client/assets/8922227/a78dd94c-bb85-4f9d-9c3b-22f707f1bbf4)
