### ISSUE TITLE
Multiple planner on roadmap page

### ISSUE THREAD

**Issue by MFYLM** [icssc/peterportal-client#266]
On roadmap page, it would be nice to allow users to have multiple four year plans to try out.

**Comment by ethanwong16** [comment]
<img width="1439" alt="Screen Shot 2023-02-25 at 18 00 34" src="https://user-images.githubusercontent.com/57075492/221388186-0a00e933-bb9d-448a-8cbc-b6ddb126fd47.png">

Currently users only have one planner where they add their years to.  This PR should explore allowing users to have multiple planners, each capable of containing multiple years.

The first step should be to update the `roadmapSlice.ts` redux file to add support for multiple planners, similar to how there is currently support for multiple years and quarters.

The second step is to create front end changes to add toggling between planners (similar to how AntAlmanac allows toggling between schedules).
