### ISSUE TITLE
Add confirmation when deleting review on reviews page, and ability to update review

### ISSUE THREAD

**Issue by advayanand** [icssc/peterportal-client#273]
- [ ] Delete review confirmation
- [ ] Update review

**Comment by ethanwong16** [comment]
Dependent on #270

**Comment by ethanwong16** [comment]
@advayanand  please update @SenghoungLim once this is resolved, thanks!

**Comment by ethanwong16** [comment]
Dependent on issue #243 to attempt logging in on staging instance
