### ISSUE TITLE
Investigate : Peter's Roadmap drag to remove classes

### ISSUE THREAD

**Issue by ethanwong16** [icssc/peterportal-client#279]
Feedback from Google Forms

> It would be nice if removing a class via dragging prompted an are you sure message. I keep on accidentally removing my classes when I miss dragging it to another quarter and then I forget which class I just removed.

**Comment by KevinWu098** [comment]
From #328 (duplicate):

> I think the best implementation would be to just reset the course to it's origin quarter. Since no trash can modal or some similar UI indicator pops up when dragging, it seems unintuitive that the course get Thanos-ed. 

> I'll also note that the current UI behavior is: Drag outside of a quarter -> it snaps back -> it gets Thanos-ed without any indicator. 

> An "are you sure" popup, as suggested, could work, but that feels unnecessary since the issue is already odd. Anteater Pathway and Zot4Plan (RIP) don't have similar features AFAIK.

![Courses get Thanos-ed](https://github.com/icssc/peterportal-client/assets/100006999/4951904f-f23f-477d-9e77-fb56741c6cdd)
