### ISSUE TITLE
Update message once staging instance is created for PR 

### ISSUE THREAD

**Issue by ethanwong16** [icssc/peterportal-client#283]
Currently in [./github/workflows/build-and-deploy.yml](https://github.com/icssc/peterportal-client/blob/master/.github/workflows/build-and-deploy.yml) , there is a message linking to the staging instance URL once it is deployed.

However, it usually takes a couple minutes for the instance to be successfully deployed, until which the link will display an error message.

This issue involves updating the message with a new line explaining this.
<img width="784" alt="Screen Shot 2023-04-21 at 16 27 37" src="https://user-images.githubusercontent.com/57075492/233748526-458678cc-ad64-4204-b272-b8fd1cd48268.png">

**Comment by js0mmer** [comment]
Copying my response from #298 
> Closing for now since it no longer seems to be necessary with our current infrastructure (deploying with SST). Instance seems to be up as soon as the link is commented now.
