### ISSUE TITLE
Search Optimization

### ISSUE THREAD

**Issue by aahei** [icssc/peterportal-client#294]
`site\src\component\SearchModule\SearchModule.tsx`

Search optimization
  - Currently sending a query request for every input change
  - Goal is to have only one query request pending
  - Use setTimeout/clearTimeout to keep track of pending query request

**Comment by js0mmer** [comment]
Looking at the code, it seems like this has [already been implemented](https://github.com/icssc/peterportal-client/blob/0605699dee898dc522c869d0e4fd0450988f5874/site/src/component/SearchModule/SearchModule.tsx#LL78C2-L87C6) but the TODO comment was never deleted.
