### ISSUE TITLE
Redundant report form and review form thank you message

### ISSUE THREAD

**Issue by js0mmer** [icssc/peterportal-client#318]
Both the review form and report form display the exact same copy-and-pasted thank you message with the exact same styles defined in the report form and review form scss files. This is redundant and it would be better to have a separate component and stylesheet for this message that is reused by both forms.

![thank you message](https://github.com/icssc/peterportal-client/assets/8922227/5057cae9-f0fd-4d20-9ebc-d1b5a0ed010b)

**Comment by vinnyho** [comment]
Could I take this issue?
