### ISSUE TITLE
Duplicate Prerequisites

### ISSUE THREAD

**Issue by KevinWu098** [icssc/peterportal-client#343]
<img width="740" alt="Screenshot 2023-08-08 at 3 46 23 PM" src="https://github.com/icssc/peterportal-client/assets/100006999/ecdd4cef-9fc6-46ae-954d-82cf498650f5">

Stats 67 requires "AP CALCULUS BC" whereas Math 3A requires "AP Calculus BC" resulting in what is essentially duplicate prerequisites which both need to be entered. Will need to investigate further to determine where the error is originating from, but my guess would be that WebSOC is not particularly consistent with how they write their Prereqs...

**Comment by js0mmer** [comment]
Would have to see if the PPAPI rewrite addresses this. #238 is also kind of related

**Comment by KevinWu098** [comment]
> Would have to see if the PPAPI rewrite addresses this. #238 is also kind of related

I'll ask @ecxyzzy about it!

**Comment by KevinWu098** [comment]
> ecxyzzy — 08/08/2023 5:35 PM
yeah one of the main goals of the rewrite was to resolve the slew of data inconsistency issues in the old API. I'll probably start migrating it over once the normalized time changes get merged in

From Eddy ^
