### ISSUE TITLE
Sort course/professor dropdown options in grade distribution alphabetically

### ISSUE THREAD

**Issue by js0mmer** [icssc/peterportal-client#354]
Currently it is in a seemingly arbitrary order for some courses/professors.

![image](https://github.com/icssc/peterportal-client/assets/8922227/f832b96b-9623-4463-a6a5-eead89594708)
![image](https://github.com/icssc/peterportal-client/assets/8922227/276e27ac-0c33-40cb-a99a-b26587d72b5c)

**Comment by vinnyho** [comment]
Could I take this issue?

**Comment by js0mmer** [comment]
> Could I take this issue?

Yes
