### ISSUE TITLE
Round instructor rating to 2 decimal points in course popup

### ISSUE THREAD

**Issue by js0mmer** [icssc/peterportal-client#371]
The instructor rating on the course popup on the search page can get really long. ICS 46 for example:

![image](https://github.com/icssc/peterportal-client/assets/8922227/4ced5e17-8f38-41a8-ae2f-23a31525ad56)

**Comment by IsaacNguyen** [comment]
I can pick this one up!

**Comment by vinnyho** [comment]
Could I take this problem?

**Comment by js0mmer** [comment]
> Could I take this problem?

Yes, go ahead!

**Comment by vinnyho** [comment]
> Yes, go ahead!
Thank you. I tested this on my local setup and noticed that "Current Instructors" didn't appear in the course popup, so I'm not entirely sure if this solution is 100% effective. However, based on the rest of the code, I believe this should resolve the issue.
      <span className="search-popup-carousel-score">{score.score == -1 ? '?' : score.score.toFixed(2)}</span>

What are your thoughts on this? Any additional insights would be appreciated.
<img width="509" alt="Screenshot 2024-09-23 at 5 53 17 PM" src="https://github.com/user-attachments/assets/5d8d5216-d851-46d2-b9f8-66a6b0c5f5ca">

**Comment by js0mmer** [comment]
Yes, that seems right. You can go ahead and put up a pull request.

**Comment by Awesome-E** [comment]
Closed via #485
