### ISSUE TITLE
Roadmap popovers overflow

### ISSUE THREAD

**Issue by js0mmer** [icssc/peterportal-client#373]
https://github.com/icssc/peterportal-client/assets/8922227/0c7c6985-11ae-425f-9529-a47648f22b6e

![image](https://github.com/icssc/peterportal-client/assets/8922227/5043c0a7-1b23-40bb-ab5e-4969abdf932f)

**Comment by timobraz** [comment]
I'm thinking of solving this issue by hiding this popup anytime the user scrolls in the div of all the years. This behavior is natural with other websites where scrolling hides popups automatically.

**Comment by js0mmer** [comment]
Better approach may be to add a container attribute to the overlay trigger. Should be possible then to set an appropriate z-index and hide the overflow so the popover is not visible outside of the planner.
