### ISSUE TITLE
`PLACEMENT EXAM` should not have a link

### ISSUE THREAD

**Issue by Awesome-E** [icssc/peterportal-client#393]
https://peterportal.org/course/ACENG20A

Similar to AP classes – placement exam or authorization link should not be a link.
<img width="908" alt="image" src="https://github.com/icssc/peterportal-client/assets/54484616/e73a604f-2df1-4e9f-a753-36a7b3aadb2a">

**Comment by js0mmer** [comment]
This may be resolved by #351 since PLACEMENT EXAM is no longer in the prereq tree for the new API, e.g: https://staging-351.peterportal.org/course/ACENG20A

Not sure if this is the API omitting or the catalogue chaning though and if this is prerequisite is present anywhere else.

**Comment by js0mmer** [comment]
![image](https://github.com/icssc/peterportal-client/assets/8922227/9432f5b7-ef1f-4049-a03f-7024f924ced0)

PLACEMENT EXAM is no longer in the prereq tree for any courses as of #351
