### ISSUE TITLE
Small screen layouts should not be exclusive to touch-first (mobile) devices

### ISSUE THREAD

**Issue by Awesome-E** [icssc/peterportal-client#422]
Use case: opening a split view window on desktop, I would much rather have the mobile layout than this. I think we should be using CSS media queries rather than just checking what device type the client is on when the page first loads.

<img width="300" alt="image" src="https://github.com/icssc/peterportal-client/assets/54484616/a9e3a9a7-fd4f-4e73-a0b9-1d8ffd0fa73c">

(steps to reproduce is same as the use case)

**Comment by js0mmer** [comment]
We should do away with the react-device-detect library and use an alternative that offers media query hooks for components that are conditionally rendered for mobile/desktop. This will allow re-rendering when the screen size hits a certain threshold. The developers of react-device-detect [mention some themselves in their README](https://github.com/duskload/react-device-detect#when-to-use-this-library).
