### ISSUE TITLE
"I&C SCI 46" Should be the first result for the search "ICS 46", not on page 3

### ISSUE THREAD

**Issue by Awesome-E** [icssc/peterportal-client#456]
Reproduce:
1. Search for "ICS 46"

Expected: I&C SCI 46 (Data structure implementation + analysis) shows as the first result
Actual: the course number seems to take higher priority even when not a full match, causing ICS 46 to show on page 3 for an exact search

**Comment by js0mmer** [comment]
Interesting. Never noticed this since I've never capitalized, just searched up "ics 46" which works. Short term fix is to convert query to lower case before calling websoc fuzzy search.

In the future, fuzzy search will be reworked. https://github.com/icssc/peterportal-api-next/issues/131

**Comment by js0mmer** [comment]
fixed by #505
