### ISSUE TITLE
Trim padding on mobile

### ISSUE THREAD

**Issue by js0mmer** [icssc/peterportal-client#477]
I feel like padding around the app content is too thick on mobile and we're not making the most of the screen space. We could cut it in half.

![image](https://github.com/icssc/peterportal-client/assets/8922227/9a62c476-da4a-448c-bc07-b5c65abd6a9b)

![image](https://github.com/icssc/peterportal-client/assets/8922227/64b41511-a2d8-47c7-9c19-b456ead9dae4)

**Comment by Awesome-E** [comment]
Will look into this after doing skeletons
